import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './recommendations.css';
import './routes.css';
import './responsive.css';
import { GOLD_ROUTES, XP_ROUTES, routesAroundLevel } from './routes';

const ELEMENTS = ['fire', 'ice', 'earth', 'energy', 'holy', 'death', 'physical'];
const fmt = (value, digits = 2) => Number(value || 0).toLocaleString('pt-BR', { maximumFractionDigits: digits });
const percent = (value) => `${(Number(value || 0) * 100).toFixed(1).replace('.', ',')}%`;
const invalidText = (value) => value === undefined || value === null || value === '' || /^(undefined|null)([-–].*)?$/i.test(String(value).trim());
const displayText = (value) => { if (invalidText(value)) return ''; if (Array.isArray(value)) return value.filter((item) => !invalidText(item)).join(', '); if (typeof value === 'object') return ''; const text = String(value); return /\bundefined\b|\bnull\b|\[object Object\]/i.test(text) ? '' : text; };
const rangeText = (min, max) => { const first = displayText(min); const second = displayText(max); if (first && second) return `${first}–${second}`; return first || second || '—'; };
const usefulEntries = (object) => Object.entries(object || {}).filter(([key, value]) => !['color', 'class', 'classname', 'icon', 'hash'].includes(key.toLowerCase()) && !invalidText(value) && !/^#/.test(String(value).trim()));

function App() {
  const [payload, setPayload] = useState(null);
  const [library, setLibrary] = useState(null);
  const [activeSection, setActiveSection] = useState('hunts');
  const [query, setQuery] = useState('');
  const [levelFilter, setLevelFilter] = useState('all');
  const [sort, setSort] = useState('stage');
  const [page, setPage] = useState(1);
  const [selectedHunt, setSelectedHunt] = useState(null);
  const [level, setLevel] = useState('');
  const [levelDraft, setLevelDraft] = useState('');
  const [levelEditorOpen, setLevelEditorOpen] = useState(false);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const pageSize = 12;

  useEffect(() => {
    Promise.all([
      fetch('/data/hunts.json').then((r) => r.json()),
      fetch('/data/bestiary.json').then((r) => r.json()),
      fetch('/data/items.json').then((r) => r.json()),
      fetch('/data/spells-runes.json').then((r) => r.json()),
      fetch('/data/vocations.json').then((r) => r.json()),
      fetch('/data/specialties.json').then((r) => r.json()),
      fetch('/data/alchemy-forge.json').then((r) => r.json()),
      fetch('/data/manifesto.json').then((r) => r.json()),
    ]).then(([huntsData, bestiary, items, spellsRunes, vocations, specialties, alchemyForge, manifesto]) => {
      setPayload(huntsData);
      setLibrary({ bestiary, items, spellsRunes, vocations, specialties, alchemyForge, manifesto });
    });
  }, []);

  const hunts = useMemo(() => {
    if (!payload) return [];
    const result = payload.hunts.filter((hunt) => {
      const matchesQuery = hunt.name.toLowerCase().includes(query.toLowerCase());
      const matchesLevel = levelFilter === 'all' || (levelFilter === 'early' && hunt.recLevel <= 50) || (levelFilter === 'advanced' && hunt.recLevel > 50);
      return matchesQuery && matchesLevel;
    });
    return result.sort((a, b) => {
      if (sort === 'xp') return b.efficiency.xpPerHp - a.efficiency.xpPerHp;
      if (sort === 'gold') return b.efficiency.totalGoldPerHp - a.efficiency.totalGoldPerHp;
      if (sort === 'hp') return a.hp - b.hp;
      return a.stage - b.stage;
    });
  }, [payload, query, levelFilter, sort]);

  useEffect(() => setPage(1), [query, levelFilter, sort]);
  const visibleHunts = hunts.slice((page - 1) * pageSize, page * pageSize);
  const pages = Math.max(1, Math.ceil(hunts.length / pageSize));

  const recommendations = useMemo(() => level ? { xp: routesAroundLevel(XP_ROUTES, Number(level)), gold: routesAroundLevel(GOLD_ROUTES, Number(level)) } : null, [level]);

  function saveLevel(event) {
    event.preventDefault();
    const parsed = Number(levelDraft);
    if (Number.isInteger(parsed) && parsed > 0) {
      setLevel(parsed);
      setLevelEditorOpen(false);
    }
  }

  if (!payload || !library) return <div className="loading-screen"><div className="sigil">✦</div><p>CARREGANDO BESTIÁRIO...</p></div>;

  return <div className="wiki-app">
    <header className="mobile-header"><Logo /><button className="mobile-menu" aria-label="Abrir menu" aria-expanded={mobileNavOpen} onClick={() => setMobileNavOpen((open) => !open)}>{mobileNavOpen ? '×' : '☰'}</button></header>
    <aside className={`sidebar ${mobileNavOpen ? 'mobile-open' : ''}`}>
      <Logo />
      <div className="server-status"><span /> BESTIÁRIO ONLINE</div>
      <nav className="main-nav">
        <NavButton active={activeSection === 'hunts'} icon="🗡️" label="Hunts recomendadas" onClick={() => { setActiveSection('hunts'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'bestiary'} icon="🐉" label="Bestiário e chefes" onClick={() => { setActiveSection('bestiary'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'items'} icon="🎒" label="Itens e loot" onClick={() => { setActiveSection('items'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'spells'} icon="✨" label="Magias e runas" onClick={() => { setActiveSection('spells'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'vocations'} icon="🛡️" label="Vocações" onClick={() => { setActiveSection('vocations'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'specialties'} icon="🧭" label="Especialidades" onClick={() => { setActiveSection('specialties'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'alchemy'} icon="🧪" label="Poções e forja" onClick={() => { setActiveSection('alchemy'); setMobileNavOpen(false); }} />
        <NavButton active={activeSection === 'manifesto'} icon="📜" label="Sobre os dados" onClick={() => { setActiveSection('manifesto'); setMobileNavOpen(false); }} />
      </nav>
      <div className="sidebar-bottom"><div className="version">IDLE HERO WIKI <b>v0.1</b></div><p>Uma referência feita pela comunidade.</p></div>
    </aside>

    <main className="content">
      <div className="topline"><div className="crumb">WIKI <span>/</span> {activeSection === 'hunts' ? 'HUNTS' : activeSection.toUpperCase()}</div><div className="data-source">● DADOS DO JOGO <span>•</span> ATUALIZADO EM 03 AGO 2026</div></div>
      {activeSection === 'hunts' ? <>
        <section className="hero-heading"><div><div className="section-kicker"><span /> GUIA DE PROGRESSÃO</div><h1>Hunts recomendadas</h1><p>Encontre as melhores criaturas para evoluir, farmar ouro e avançar pelo estágio.</p></div><div className="hero-count"><strong>{payload.totalHunts}</strong><span>HUNTS<br />CATALOGADAS</span></div></section>
        <section className="level-card"><div className="level-card-icon">⌁</div><div className="level-card-copy"><span>PERSONALIZE SUA RECOMENDAÇÃO</span><strong>{level ? `Recomendações para level ${fmt(level, 0)}` : 'Descubra onde caçar agora'}</strong><p>{level ? 'Resultados calculados para o level anterior, atual e seguinte.' : 'Informe seu level para encontrar as melhores hunts de XP e Gold.'}</p></div>{!levelEditorOpen && <button className="level-action" onClick={() => { setLevelDraft(level); setLevelEditorOpen(true); }}>{level ? 'Alterar level' : 'Informar meu level'} <b>→</b></button>}{levelEditorOpen && <form className="level-form" onSubmit={saveLevel}><label>SEU LEVEL<input autoFocus type="number" min="1" value={levelDraft} onChange={(event) => setLevelDraft(event.target.value)} placeholder="Ex.: 120" /></label><button type="submit">Aplicar</button></form>}</section>
        {level && <RecommendationSection recommendations={recommendations} onOpen={(route) => setSelectedHunt(payload.hunts.find((hunt) => hunt.name.toLowerCase() === route.name.toLowerCase()) || null)} />}
        <section className="stat-strip"><Stat label="HUNTS CATALOGADAS" value={payload.hunts.length} /><Stat label="ESTÁGIO MÁXIMO" value={Math.max(...payload.hunts.map((hunt) => hunt.stage))} /><Stat label="NÍVEL RECOMENDADO MÁXIMO" value={Math.max(...payload.hunts.map((hunt) => hunt.recLevel))} /><Stat label="COM LOOT REGISTRADO" value={payload.hunts.filter((hunt) => hunt.lootPool?.length).length} /></section>
        <section className="toolbar"><div className="search-field"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar criatura..." /></div><select value={levelFilter} onChange={(e) => setLevelFilter(e.target.value)}><option value="all">Todos os níveis</option><option value="early">Níveis iniciais (até 50)</option><option value="advanced">Níveis avançados (51+)</option></select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="stage">Ordenar por estágio</option><option value="xp">Melhor XP / HP</option><option value="gold">Melhor Gold / HP</option><option value="hp">Menor HP</option></select></section>
        <section className="table-card"><div className="table-heading"><div><h2>Catálogo de criaturas</h2><p>{hunts.length} resultado{hunts.length === 1 ? '' : 's'} encontrados</p></div><span className="legend"><i className="legend-dot" /> fraqueza elemental</span></div><div className="table-scroll"><table><thead><tr><th>CRIATURA</th><th>ESTÁGIO</th><th>REC. LVL</th><th>HP</th><th>XP / KILL</th><th>GOLD / KILL</th><th>XP / HP</th><th>ELEMENTOS</th><th /></tr></thead><tbody>{visibleHunts.map((hunt) => <HuntRow key={`${hunt.stage}-${hunt.name}`} hunt={hunt} onOpen={() => setSelectedHunt(hunt)} />)}</tbody></table></div>{visibleHunts.length === 0 && <div className="empty">Nenhuma criatura encontrada para esses filtros.</div>}<div className="pagination"><span>Mostrando {hunts.length ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, hunts.length)} de {hunts.length}</span><div><button disabled={page === 1} onClick={() => setPage(page - 1)}>←</button><b>{page} / {pages}</b><button disabled={page === pages} onClick={() => setPage(page + 1)}>→</button></div></div></section>
      </> : <KnowledgeSection section={activeSection} library={library} />}
      <footer><span>✦</span> IDLE HERO WIKI <i>feito para consultar, descobrir e jogar melhor.</i> <a href="https://github.com/raryson/iddle-hero-wiki" target="_blank" rel="noreferrer">ver no GitHub</a> <small>Projeto open source — contribuições são bem-vindas.</small></footer>
    </main>
    {selectedHunt && <HuntModal hunt={selectedHunt} onClose={() => setSelectedHunt(null)} />}
  </div>;
}

function Logo() { return <div className="logo"><div className="logo-mark">✦</div><div><strong>IDLE HERO</strong><span>COMMUNITY WIKI</span></div></div>; }
function NavButton({ active, icon, label, onClick, soon }) { return <button className={`nav-button ${active ? 'active' : ''}`} onClick={onClick}><span className="nav-icon">{icon}</span>{label}{soon && <small>EM BREVE</small>}</button>; }
function Stat({ label, value }) { return <div className="stat"><span>{label}</span><strong>{fmt(value, 0)}</strong></div>; }
function CopyHuntButton({ name }) { const [copied, setCopied] = useState(false); async function copyName(event) { event.stopPropagation(); try { await navigator.clipboard.writeText(name); } catch { const area = document.createElement('textarea'); area.value = name; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); } setCopied(true); window.setTimeout(() => setCopied(false), 1800); } return <><button type="button" className={`copy-hunt ${copied ? 'copied' : ''}`} onClick={copyName} aria-label={`Copiar nome da hunt ${name}`} title={copied ? 'Nome copiado' : 'Copiar nome'}>{copied ? '✓' : '⧉'}</button>{copied && <div className="copy-toast" role="status">Nome da hunt copiado para o clipboard</div>}</>; }
function HuntRow({ hunt, onOpen }) { const weaknesses = Object.entries(hunt.elements || {}).filter(([, value]) => value < 0).slice(0, 3); return <tr onClick={onOpen}><td><div className="hunt-name-cell"><strong className="creature-name">{hunt.name}</strong><CopyHuntButton name={hunt.name} />{hunt.lootPool?.length > 0 && <small className="loot-tag">LOOT</small>}</div></td><td><span className="stage">{hunt.stage}</span></td><td>{hunt.recLevel}</td><td className="mono">{fmt(hunt.hp, 0)}</td><td className="mono">{fmt(hunt.xpBase, 0)}</td><td className="mono">{fmt(hunt.expectedTotalGoldPerKill)}</td><td className="green mono">{percent(hunt.efficiency.xpPerHp)}</td><td><div className="elements">{weaknesses.length ? weaknesses.map(([name, value]) => <span className={`element ${name}`} key={name}>{name} {value}%</span>) : <span className="no-element">—</span>}</div></td><td className="arrow">↗</td></tr>; }
function HuntModal({ hunt, onClose }) { return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(e) => e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="section-kicker"><span /> DETALHES DA CRIATURA</div><div className="modal-title-row"><h2>{hunt.name}</h2><CopyHuntButton name={hunt.name} /></div><p className="modal-sub">ESTÁGIO {hunt.stage} · NÍVEL RECOMENDADO {hunt.recLevel}</p><div className="detail-grid"><Detail label="Pontos de vida" value={fmt(hunt.hp, 0)} /><Detail label="XP por kill" value={fmt(hunt.xpBase, 0)} /><Detail label="Gold por kill" value={fmt(hunt.expectedTotalGoldPerKill)} /><Detail label="XP por HP" value={percent(hunt.efficiency.xpPerHp)} /><Detail label="Gold total / HP" value={hunt.efficiency.totalGoldPerHp.toFixed(3)} /><Detail label="Loot registrado" value={`${hunt.lootPool?.length || 0} itens`} /></div><div className="modal-block"><span>RESISTÊNCIAS E FRAQUEZAS</span><div className="modal-elements">{Object.entries(hunt.elements || {}).map(([key, value]) => <span className={`element ${value < 0 ? key : 'resist'}`} key={key}>{key} {value > 0 ? '+' : ''}{value}%</span>)}{!Object.keys(hunt.elements || {}).length && <em>Sem modificadores registrados.</em>}</div></div><div className="modal-block"><span>IMUNIDADES</span><p>{hunt.immunities?.length ? hunt.immunities.join(' · ') : 'Nenhuma imunidade registrada.'}</p></div></div></div>; }
function Detail({ label, value }) { return <div className="detail"><span>{label}</span><strong>{value}</strong></div>; }
function RecommendationSection({ recommendations, onOpen }) {
  return <section className="recommendations"><div className="recommendation-heading"><div><div className="section-kicker"><span /> RECOMENDAÇÕES POR LEVEL</div><h2>Rota sugerida para você</h2><p>Uma hunt anterior, a faixa atual e a próxima, seguindo as rotas estratégicas da wiki.</p></div><span className="recommendation-note">ROTA CONFIGURADA</span></div><div className="recommendation-columns"><RecommendationGroup title="RUSH DE XP" accent="xp" routes={recommendations.xp} onOpen={onOpen} /><RecommendationGroup title="PROFIT POR LEVEL" accent="gold" routes={recommendations.gold} onOpen={onOpen} /></div></section>;
}
function RecommendationGroup({ title, accent, routes, onOpen }) {
  return <div className={`recommendation-group ${accent}`}><div className="group-title"><span>{accent === 'xp' ? '✦' : '◈'}</span><strong>{title}</strong><small>MELHOR HUNT DA FAIXA</small></div><div className="recommendation-levels">{routes.map(({ route, relation }) => <div className="route-card" role="button" tabIndex="0" key={`${accent}-${route.start}-${route.name}`} onClick={() => onOpen(route)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onOpen(route); }}><div className="route-card-heading"><span>{relation}</span><strong>{route.start}–{route.end}</strong></div><div className="route-name-row"><b className="route-name">{route.name}</b><CopyHuntButton name={route.name} /></div><small>FASE {route.stage} · {route.element}</small><div className="route-metrics"><span>{route.multiplier}</span><strong>{accent === 'xp' ? `${route.perHour} XP/h` : `${route.goldPerHour} Gold/h`}</strong></div></div>)}</div></div>;
}
function KnowledgeSection({ section, library }) {
  const [query, setQuery] = useState('');
  const info = {
    bestiary: ['Bestiário e chefes', 'Criaturas especiais, chefes e bônus de prey.'],
    items: ['Itens e loot', 'Equipamentos, atributos e valores do catálogo do jogo.'],
    spells: ['Magias e runas', 'Magias, runas, vocações e fórmulas de combate.'],
    vocations: ['Vocações', 'Atributos de progressão e habilidades de cada vocação.'],
    specialties: ['Roda e especialidades', 'Nós da roda, custos e especialidades disponíveis.'],
    alchemy: ['Poções e forja', 'Poções, imbuimentos, tiers e receitas de forja.'],
    manifesto: ['Sobre os dados', 'Origem, cobertura e convenções utilizadas nesta wiki.'],
  }[section];
  return <section className="knowledge-page"><div className="knowledge-hero"><div><div className="section-kicker"><span /> BASE DE CONHECIMENTO</div><h1>{info[0]}</h1><p>{info[1]}</p></div><div className="knowledge-mark">✦</div></div>{section !== 'manifesto' && section !== 'vocations' && <div className="knowledge-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Buscar em ${info[0].toLowerCase()}...`} /></div>}{section === 'bestiary' && <BestiaryContent data={library.bestiary} query={query} />}{section === 'items' && <ItemsContent data={library.items} query={query} />}{section === 'spells' && <SpellsContent data={library.spellsRunes} query={query} />}{section === 'vocations' && <VocationsContent data={library.vocations} />}{section === 'specialties' && <SpecialtiesContent data={library.specialties} query={query} vocations={library.vocations.vocations || []} />}{section === 'alchemy' && <AlchemyContent data={library.alchemyForge} query={query} />}{section === 'manifesto' && <ManifestoContent data={library.manifesto} />}</section>;
}
function BestiaryContent({ data, query }) { const bosses = data.bosses.filter((boss) => boss.name.toLowerCase().includes(query.toLowerCase())); return <><KnowledgeStats values={[[data.summary.boss_count, 'CHEFES'], [data.summary.prey_bonus_type_count, 'BÔNUS PREY'], [data.summary.bestiary_threshold_bracket_count, 'FAIXAS DO BESTIÁRIO']]} /><KnowledgeTable title="Chefes catalogados" columns={['Nome', 'Level', 'HP', 'XP', 'Gold', 'Raça']} rows={bosses.map((boss) => [boss.name, boss.rec_level, fmt(boss.hp, 0), fmt(boss.xp, 0), fmt(boss.gold, 0), boss.race || '—'])} /><KnowledgeCards title="Tipos de bônus de prey" items={data.prey_bonus_types.map((bonus) => ({ title: bonus.short_label, text: bonus.description }))} /></>; }
function ItemsContent({ data, query }) { const items = data.items.filter((item) => `${item.name} ${item.slot || ''}`.toLowerCase().includes(query.toLowerCase())); return <><KnowledgeStats values={[[data.summary.total_items, 'ITENS'], [data.summary.configured_sell_price_count, 'VALORES DE VENDA'], [Object.keys(data.summary.by_slot || {}).length, 'SLOTS']]} /><KnowledgeTable title={`${items.length} itens encontrados`} columns={['Item', 'Slot', 'Level', 'HP', 'DPS', 'Defesa', 'Magic points']} rows={items.map((item) => [item.name, item.slot || '—', item.level ?? '—', item.hp ?? '—', item.dps ?? '—', item.def ?? '—', item.magicpoints ?? '—'])} /></>; }
function SpellsContent({ data, query }) { const spells = data.spells.filter((spell) => `${spell.name} ${spell.words} ${spell.group}`.toLowerCase().includes(query.toLowerCase())); return <><KnowledgeStats values={[[data.summary.total_spells, 'MAGIAS'], [data.summary.total_runes, 'RUNAS'], [Object.keys(data.summary.spell_groups || {}).length, 'GRUPOS']]} /><KnowledgeTable title="Magias" columns={['Nome', 'Palavras', 'Level', 'Mana', 'Cooldown', 'Grupo', 'Vocações']} rows={spells.map((spell) => [spell.name, spell.words, spell.level, spell.mana, spell.cooldown, spell.group, (spell.vocations || []).join(', ')])} /><KnowledgeCards title="Runas catalogadas" items={data.runes.map((rune) => ({ title: `Runa #${rune.id}`, text: usefulEntries(rune.availability).map(([key, value]) => `${key}: ${Array.isArray(value) ? value.filter((item) => !invalidText(item)).join(', ') : displayText(value)}`).filter((item) => item && !/undefined|null/i.test(item)).join(' · ') || 'Disponibilidade registrada no pacote de dados.' }))} /></>; }
function VocationsContent({ data }) { const baseVocations = data.vocations.filter((vocation) => vocation.id >= 1 && vocation.id <= 4); return <><KnowledgeStats values={[[baseVocations.length, 'VOCAÇÕES BASE'], [baseVocations.length, 'PROMOÇÕES'], [baseVocations.reduce((total, vocation) => total + (vocation.skills?.length || 0), 0), 'HABILIDADES']]} /><div className="knowledge-card-grid">{baseVocations.map((vocation) => { const promotion = data.vocations.find((candidate) => candidate.id === vocation.id + 4); return <article className="knowledge-card" key={vocation.id}><div className="card-eyebrow">VOCAÇÃO #{vocation.id}</div><h3>{vocation.name}</h3>{promotion && <div className="promotion-label">Promoção: {promotion.name}</div>}<div className="mini-stats"><span>HP ganho <b>{vocation.gainhp}</b></span><span>Mana ganha <b>{vocation.gainmana}</b></span><span>Capacidade <b>{vocation.gaincap}</b></span></div><p>{vocation.skills?.length || 0} habilidades registradas · os dados da promoção estão agrupados nesta vocação.</p></article>; })}</div></>; }
function SpecialtiesContent({ data, query, vocations }) { const specialties = data.specialties.filter((specialty) => `${specialty.name} ${specialty.description}`.toLowerCase().includes(query.toLowerCase())); const wheelQuery = query.toLowerCase(); const paths = Object.entries(data.wheel.path_metadata || {}).map(([key, meta]) => ({ key, meta, nodes: (data.wheel.nodes || []).filter((node) => node.path === key && `${node.name} ${node.key}`.toLowerCase().includes(wheelQuery)) })); return <><KnowledgeStats values={[[data.wheel.minimum_level, 'LEVEL PARA LIBERAR'], [data.wheel.maximum_active_paths, 'CAMINHOS ATIVOS'], [data.wheel.reset_cost?.gold, 'GOLD PARA RESETAR'], [data.summary.wheel_node_count, 'NÓS DA RODA']]} /><section className="wheel-overview"><div className="knowledge-panel-heading"><div><h2>Como funciona a roda</h2><p>Escolha até {data.wheel.maximum_active_paths} caminhos a partir do level {data.wheel.minimum_level}. Cada caminho evolui por anéis e os nós mais avançados exigem mais gold.</p></div></div><div className="wheel-path-grid">{paths.map(({ key, meta, nodes }) => <WheelPath key={key} pathKey={key} meta={meta} nodes={nodes} labels={data.wheel.effect_labels} />)}</div></section><WheelMultipliers data={data.wheel} vocations={vocations} /><KnowledgeCards title="Especialidades" items={specialties.map((specialty) => ({ title: specialty.name, text: specialty.description, meta: `Máximo: ${specialty.max_level}` }))} /></>; }
function WheelPath({ pathKey, meta, nodes, labels }) { const totalGold = nodes.reduce((total, node) => total + (node.total_gold_to_max || 0), 0); return <article className={`wheel-path wheel-${pathKey}`}><header><div><span className="path-label">{meta.label}</span><h3>{meta.desc}</h3></div><strong>{fmt(totalGold, 0)} gold</strong></header><div className="wheel-node-list">{nodes.map((node) => <div className="wheel-node" key={node.key}><div className="wheel-node-top"><span>Anel {node.ring}</span><b>0–{node.max}</b></div><h4>{node.name}</h4><div className="wheel-effects">{Object.entries(node.effects || {}).map(([effect, value]) => <span key={effect}>{labels[effect] || effect}: +{value}% / nível</span>)}</div><small>{fmt(node.total_gold_to_max, 0)} gold até o máximo</small></div>)}</div></article>; }
function WheelMultipliers({ data, vocations }) { const multipliers = Object.entries(data.vocation_path_multipliers || {}); const vocationList = Array.isArray(vocations) ? vocations : []; const names = Object.fromEntries(vocationList.map((vocation) => [String(vocation.id), vocation.name])); const knightPromotion = names['8']; return <section className="knowledge-panel wheel-rules"><div className="knowledge-panel-heading"><div><h2>Multiplicadores por vocação</h2><span>Quanto cada vocação paga ou aproveita em cada caminho</span></div><span>MAESTRIA ×{data.maestria_cost_multiplier}</span></div><div className="knowledge-table-scroll"><table><thead><tr><th>Vocação</th><th>Fúria</th><th>Arcano</th><th>Proteção</th><th>Precisão</th></tr></thead><tbody>{multipliers.map(([vocation, values]) => { const name = names[vocation] || `Vocação ${vocation}`; const label = vocation === '4' && knightPromotion ? `${name} (${knightPromotion})` : name; return <tr key={vocation}><td>{label}</td><td>{values.furia}×</td><td>{values.arcano}×</td><td>{values.protecao}×</td><td>{values.precisao}×</td></tr>; })}</tbody></table></div><div className="wheel-rule-note">Reset: {fmt(data.reset_cost?.gold, 0)} gold + {data.reset_cost?.points} pontos. O caminho Fúria do Knight tem limite de {data.knight_furia_weapon_damage_cap_pct}% de dano de arma.</div></section>; }
function AlchemyContent({ data, query }) { const potions = data.potions.filter((potion) => `${potion.name} ${potion.type}`.toLowerCase().includes(query.toLowerCase())); const elements = data.imbuements?.elements || []; return <><KnowledgeStats values={[[data.summary.potion_count, 'POÇÕES'], [data.summary.imbuement_element_count, 'ELEMENTOS'], [data.summary.tier_slot_count, 'SLOTS DE TIER'], [data.summary.forge_recipe_count, 'RECEITAS']]} /><ImbuementGuide data={data.imbuements} /><KnowledgeTable title="Poções" columns={['Poção', 'Tipo', 'Level', 'Custo', 'Efeito', 'Mana']} rows={potions.map((potion) => [potion.name, potion.type, potion.level, fmt(potion.cost, 0), rangeText(potion.min, potion.max), rangeText(potion.mana_min, potion.mana_max)])} /><KnowledgeCards title="Elementos de imbuimento" items={elements.map((element) => ({ title: element.label || element.name || element.key || displayText(element) || 'Elemento', text: typeof element === 'object' ? usefulEntries(element).filter(([key]) => !['name', 'key', 'label', 'icon'].includes(key)).map(([key, value]) => `${key}: ${displayText(value)}`).filter((item) => !/undefined|null/i.test(item)).join(' · ') : 'Elemento disponível para imbuimento.' }))} /><ForgeRecipes recipes={data.forge?.recipes || []} /></>; }
function ImbuementGuide({ data }) { const weapon = data.weapon || {}; const armor = data.armor || {}; return <section className="imbuement-guide"><div className="knowledge-panel-heading"><div><h2>✨ Imbuição</h2><p>Escolha o elemento pensando na hunt e no tipo de equipamento.</p></div><span>20 HORAS EQUIPADO</span></div><div className="imbuement-grid"><article className="imbuement-card weapon"><div className="card-eyebrow">ARMA · EXEMPLO INFORMADO</div><h3>Umbral Master Slayer</h3><div className="imbuement-values"><span><b>{fmt(weapon.cost_gold || 5000000, 0)}</b> Gold</span><span><b>4.509.966</b> saldo informado</span><span><b>{Math.round((weapon.duration_seconds || 72000) / 3600)}h</b> de duração</span></div><p>40% do seu golpe vira dano do elemento e ignora a armadura do monstro. Os 60% restantes continuam físicos.</p></article><article className="imbuement-card armor"><div className="card-eyebrow">ARMADURA</div><h3>Resistência elemental</h3><div className="imbuement-values"><span><b>{fmt(armor.cost_gold || 10000000, 0)}</b> Gold</span><span><b>+{armor.resistance_pct || 15}%</b> resistência</span><span><b>{Math.round((armor.duration_seconds || 72000) / 3600)}h</b> de duração</span></div><p>A imbuíção adiciona resistência ao elemento escolhido, respeitando o teto de 90% citado nos dados.</p></article></div><div className="element-picker"><span className="card-eyebrow">ELEMENTOS DISPONÍVEIS</span><div>{(data.elements || []).map((element) => <span className="element-choice" key={element.key}>{element.icon} {element.label}</span>)}</div></div><div className="imbuement-note"><strong>Como funciona o relógio</strong><span>As 20 horas contam apenas com a peça equipada. Ao guardar na mochila, o tempo congela e volta a contar quando você equipar novamente.</span><span>Contra um monstro que resiste ao elemento escolhido, a imbuição pode causar menos dano do que lutar sem nenhuma imbuição.</span></div></section>; }
function ForgeRecipes({ recipes }) { return <section className="knowledge-panel forge-panel"><div className="knowledge-panel-heading"><div><h2>Receitas de forja</h2><span>Materiais necessários para cada fusão</span></div><span>{recipes.length} receitas</span></div>{recipes.map((recipe) => <article className="forge-recipe" key={recipe.key}><div className="forge-result"><div className="card-eyebrow">RESULTADO</div><h3>{recipe.result_name}</h3><p>{recipe.type} · Tier mínimo {recipe.minimum_ingredient_tier}</p></div><div className="forge-materials"><div className="card-eyebrow">MATERIAIS NECESSÁRIOS</div><ul>{(recipe.ingredients || []).map((ingredient) => <li key={ingredient.label}><span className="material-check">✓</span><div><strong>{ingredient.label}</strong><small>{ingredient.accepted_names?.join(' / ') || 'Item aceito'} · Tier {ingredient.minimum_tier || recipe.minimum_ingredient_tier}</small></div></li>)}</ul></div><div className="forge-costs"><span><b>{recipe.ingredients?.length || 0}</b> itens</span><span><b>{fmt(recipe.forge_orbs_required, 0)}</b> orbes</span><span><b>{fmt(recipe.gold_required, 0)}</b> gold</span></div></article>)}</section>; }
function ManifestoContent({ data }) { return <><div className="manifesto-copy"><div className="section-kicker"><span /> MANIFESTO</div><p>{data.purpose}</p></div><KnowledgeCards title="Arquivos publicados" items={data.files.map((file) => ({ title: file.name, text: `${file.bytes?.toLocaleString('pt-BR') || '—'} bytes · categoria ${file.category}` }))} /><KnowledgeCards title="Notas de qualidade" items={data.quality_notes.map((note) => ({ title: note.status, text: note.note, meta: `Categoria ${note.category}` }))} /></>; }
function KnowledgeStats({ values }) { return <div className="knowledge-stats">{values.map(([value, label]) => <div className="knowledge-stat" key={label}><strong>{fmt(value, 0)}</strong><span>{label}</span></div>)}</div>; }
function KnowledgeTable({ title, columns, rows }) { return <section className="knowledge-panel"><div className="knowledge-panel-heading"><h2>{title}</h2><span>{rows.length} registros</span></div><div className="knowledge-table-scroll"><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${title}-${index}`}>{row.map((cell, cellIndex) => <td key={`${index}-${cellIndex}`}>{displayText(cell) || '—'}</td>)}</tr>)}</tbody></table></div></section>; }
function KnowledgeCards({ title, items }) { return <section className="knowledge-panel"><div className="knowledge-panel-heading"><h2>{title}</h2><span>{items.length} registros</span></div><div className="knowledge-card-grid">{items.map((item, index) => <article className="knowledge-card" key={`${title}-${item.title}-${index}`}><div className="card-eyebrow">REGISTRO {String(index + 1).padStart(2, '0')}</div><h3>{displayText(item.title) || 'Sem título'}</h3>{item.meta && <small>{displayText(item.meta)}</small>}<p>{displayText(item.text) || 'Sem informação adicional.'}</p></article>)}</div></section>; }
function ComingSoon({ title }) { return <section className="coming-soon"><div className="big-sigil">✦</div><div className="section-kicker"><span /> PRÓXIMA SEÇÃO</div><h1>{title}</h1><p>Esta área da wiki está sendo preparada. A base de dados já está estruturada para receber novos conteúdos.</p></section>; }

createRoot(document.getElementById('root')).render(<App />);
